### PR TITLE
Fix bug: Overlapping booking being accepted.

### PR DESCRIPTION
**Pull request by iyioon**
This is a urgent fix, hence many of the test cases for booking period has been removed.
Also now, a booking with equal check in and check out time is not accepted.

**Todo**:

- Add test cases for booking Period
- Refactor the rest of booking period test cases (some were not refactored)

### CODE REVIEW

**Comment by RB9823** [comment]
LGTM

**Comment by markgcera** [comment]
Close #228

**Comment by markgcera** [comment]
@iyioon , can I confirm with you that this PR also fixes #226?

**Comment by markgcera** [comment]
This PR also fixes issue #222. Close #222.

**Comment by markgcera** [comment]
Close #232

**Pull request merged**
